### PR TITLE
Pull request for suport for asturian language

### PR DESCRIPTION
**Pull request by chrismilleresp**

### CODE REVIEW

**Comment by Mte90** [comment]
What is the language code? es_AST?
That glossary is available online for glotdictjson?

**Comment by chrismilleresp** [comment]
Hello Daniele.
The language code is ast and the glossary is
https://translate.wordpress.org/projects/wp/dev/ast/default/glossary

Thank you!

2016-05-04 14:57 GMT+02:00 Daniele Scasciafratte <notifications@github.com>:

**Comment by Mte90** [comment]
Ok perfect I have added asturian in GlotDictJSON so this pr is not required.
Now I continue to update the glossary :-)

**Comment by Mte90** [comment]
I was forgetting the next 1.0.8 will have also the asturian language :-)

**Comment by chrismilleresp** [comment]
Thank you!! This tool is impressive and will help a lot new translators! :)

**Pull request closed without merging**
