### PR TITLE
QuickLinks & Consistency Suggestions

### PR DESCRIPTION
**Pull request by vlad-timotei**
# QuickLinks

QuickLinks_demo

 - Many times, we’d like to either open or copy one of the links in the Hamburger menu: Permalink, History or Consistency and we can do that, but I’d like an easier way to do that. This adds quick icon links to either copy or open in a new tab that link.
 - User clicks on any of those 3 right icons and a new tab is opened.
 - If a user clicks on the Clipboard icon, that gets blue and a + pops up, suggesting that now you can press on those three icons and the link will be copied to clipboard.
- The toggle between copy/open is stored as a preference and it is also updated for all menus in that page when the user does the toggle.

# Consistency Suggestions
Consistency_demo
 - Translation Memory sometimes has bad translations (see #meta5340). This shows Consistency translations directly in the editor panel.
 - Loading a Consistency page takes a few seconds or more depending on the query, so without an API, it's not efficient load all consistency suggestions for all strings on a page when the page loads.
- User clicks a button or a keyboard shortcut (`Alt + C`) to start loading the consistency suggestions for a string.
- The suggestions load as any other suggestions in that area - they can be copied and also the state of the suggestion block (open/closed) is being stored, as part of GP core features.

## Testing
**QuickLinks**
- Open each link in new tab
- Copy each link
- Remember copy toggle status

**Consistency Suggestions**
- Loading suggestions
- Copy to editor
- Remember details state
- Alt + C keyboard shortcut

### Browser tested
- Microsoft Edge 92.0.902.62
- Google Chrome 92.0.4515.107
- Firefox 90.0.2 (could not test keyboard shortcut)
- Opera 77.0.4054.277
- Brave 1.27.109

### CODE REVIEW

**Review by vlad-timotei — COMMENTED** [review]
I went for the simplest most intuitive keyboard combination, but if GD has another set of standard keyboard shortcuts, we can change it to something that fits other shortcuts.

**Comment by Mte90** [comment]
I am on vacation so I don't know when I can check this pr but in the meantime thanks!

**Review by Mte90 — CHANGES_REQUESTED** [review]
To me the code is good.
To approve it I need that you update the Readme with this new stuff and and also adding your name :-)
So I can update the changelog and evaluate if release a new major or wait few more days for new stuff coming.

**Review by Mte90 — APPROVED** [review]
Tested with Firefox and works everything.

I think that soon we will need to address `addEvtListener` and replace the other cases with the jquery code to move to vanilla.

**Pull request merged**
