### PR TITLE
Changing CTRL+SHIFT+N to CTRL+SHIFT+X

### PR DESCRIPTION
**Pull request by NekoJonez**
I think I changed it everywhere, I suggest this change since like I said in: #280 
CTRL+SHIFT+N opens incognito mode here.... Maybe it's an AZERTY thing but CTRL+SHIFT+X isn't a hotkey for anything in the browsers so yeah.

https://defkey.com/search?irq=Ctrl+%2B+Shift+%2B+x

### CODE REVIEW

**Comment by webaxones** [comment]
Hi,
CTRL+SHIFT+M is a Chrome global shortcut:
https://developer.chrome.com/docs/devtools/shortcuts/#global

**Comment by NekoJonez** [comment]
> Hi,
> CTRL+SHIFT+M is a Chrome global shortcut:
> https://developer.chrome.com/docs/devtools/shortcuts/#global

And I overlooked that :o 

I changed it to CTRL+SHIFT+V, which isn't a shortcut so far as I can see.

**Comment by webaxones** [comment]
Well…
On windows, CTRL Shift V is a shortcut to paste text without formating… so often used on the web.
Sorry but I know that looking for an unused shortcut is a nightmare ^^'

**Comment by NekoJonez** [comment]
> Well…
> On windows, CTRL Shift V is a shortcut to paste text without formating… so often used on the web.
> Sorry but I know that looking for an unused shortcut is a nightmare ^^'
> I just found this list that can help you:
> http://dmcritchie.mvps.org/firefox/keyboard.htm
> (last update: 01/26/2020)

That site is 404'ing here... 

And you have a point. I picked v because i felt like ... Its only in text editors and since this tool is only for translate.wp.org

But I will look for another key soon.

**Comment by NekoJonez** [comment]
> Well…
> On windows, CTRL Shift V is a shortcut to paste text without formating… so often used on the web.
> Sorry but I know that looking for an unused shortcut is a nightmare ^^'
> I just found this list that can help you:
> http://dmcritchie.mvps.org/firefox/keyboard.htm
> (last update: 01/26/2020)

https://defkey.com/search

I will use this site. This is quite helpful.

**Comment by NekoJonez** [comment]
@webaxones I think I found one. CTRL+SHIFT+X

**Comment by Mte90** [comment]
Good catch!

**Pull request merged**
