### PR TITLE
Adding a sticky header

### PR DESCRIPTION
**Pull request by webaxones**
Adding a sticky header to keep controls availables when we scroll.
The sticky can be activated or deactivated directly from the toggle field in the title because from experience I have noticed that sometimes you want to switch depending on the work you are doing.
And I deliberately chose to make it active by default otherwise users don't realize that a new feature has just been added. They can deactivate it at any time.
I took the opportunity to improve the style of the buttons next to the select Bulk actions a little by giving them the same height because the design was not really optimized.
And I also declared a new global gd_user that we will be able to use to check different things:
```javascript
const gd_user = {
	is_translator:      false,
	is_editor:          false,
	is_connected:       false,
	is_on_translations: false,
}
```
So we have the CSS classes for styling depending on what the user is, and a global variable that we can check to make processes also depending on what the user is.

Tested on Chrome and Firefox.

stickyheader

### CODE REVIEW

**Comment by Mte90** [comment]
Nice I see in the code the localstorage to save the settings but I don't find the code to show the option.

**Comment by webaxones** [comment]
I should indeed have detailed the proposal:
The gd_build_sticky_header function takes care of both gathering the different elements in a container and at the same time creating the toggle field to register the option. This is a special case of an option that it is better to have it directly in front of you rather than in the settings so that it can be switched more easily. Because that's what I noticed: users change depending on what they do with translations. Sometimes they want the sticky header, sometimes they don't. Classic settings are more used for something definitive that you adjust once. That's why I made a toggle in the title.

Notices have been changed to no longer be added before the table but inside the container before the table. Because even if the user chooses not to make the container sticky, the items are still placed there. And the display of notices is slightly modified when the container is sticky:

noticesinsticky

**Review by vlad-timotei — COMMENTED** [review]
I have a question about `const gd_notices_container` usage. 

If we follow the script flow, first, it's set as a constant in `glotdict.js`, storing the `#gd-notices-container` div. That's perfect.
https://github.com/Mte90/GlotDict/blob/35d22f55dc3e496b1cab3b8fe87028360d07e154/js/glotdict.js#L25-L26

Then, in `gloditct-functions.js` inside `gd_wait_table_alter()`, the same name constant is used, but it seems that is never used inside that function. So, can this line be removed?
https://github.com/Mte90/GlotDict/blob/35d22f55dc3e496b1cab3b8fe87028360d07e154/js/glotdict-functions.js#L368-L369

Later on, in the same file, inside `gd_build_sticky_header()`, the same name constant is used to store the same element that is already stored in the constant. I might be missing something, but could we declare `gd_notices_container` as a global in eslint, remove this line and spare a `querySelector()` call?  
https://github.com/Mte90/GlotDict/blob/35d22f55dc3e496b1cab3b8fe87028360d07e154/js/glotdict-functions.js#L526

**Comment by webaxones** [comment]
> Then, in gloditct-functions.js inside gd_wait_table_alter(), the same name constant is used, but it seems that is never used inside that function. So, can this line be removed?

Tu as tout à fait raison. C'est un oubli de ma part quand j'hésitais entre modifier le code des notices pour les placer dans le conteneur, ce que j'ai fait, ou les redéplacer à la détection de leur création dans le mutation observer. J'ai oublié de supprimer cette ligne. Good catch! :) 

> but could we declare gd_notices_container as a global in eslint...

Nope. 
The declaration to ESLint is just used to let the linter know the scope of the variables. So that would need to also declare this variable globally.
But the scope of the variables influences the performance: a variable declared in a function or even in a simple condition (like if) is limited to that function or that condition. A variable declared globally will be accessible throughout the project but will consume more and therefore the project will be less efficient.

https://dev.to/alwarg/how-variable-scoping-affects-the-performance-4eg2

> 1) keep the variables within the current scope as much as possible

which is usually done

> 2) If rule 1 is not possible, then cache the outer scoped variables

over-optimization (which would greatly complicate our task given the architecture of GlotDict)

**Comment by vlad-timotei** [comment]
> So that would need to also declare this variable globally.
It is already declared globally. It's not inside a function. I only mentioned eslint because it should also be declared there.

**Review by vlad-timotei — COMMENTED** [review]
Changing the topic, I love the `gd_user` object! ❤️ It's super useful for a lot of later checks. The consistency of this is genius! And it's very clear to understand how you can use it. Well done!

Regarding the call to  `gd_build_sticky_header()`, I wonder why you call it when user is connected only? One would argue that it can be useful for not logged in users as well. But that is subjective. Up to you.
https://github.com/Mte90/GlotDict/blob/35d22f55dc3e496b1cab3b8fe87028360d07e154/js/glotdict.js#L131
My question is if we should add `gd_user.is_on_translations` as a condition ( here or inside the function ), instead of the one inside the function.

Line 510 from `gd_build_sticky_header()` has the same value as `gd_user.is_on_translations`, based on [this table](https://docs.google.com/document/d/1S2smv7Oq6H_Qox4PDAop0A7qDodq2qsmN2qVbi1Npuo/edit#bookmark=id.5x1vwc1ppxjl) that we hope to stay true for as long as possible. 
https://github.com/Mte90/GlotDict/blob/35d22f55dc3e496b1cab3b8fe87028360d07e154/js/glotdict-functions.js#L509-L511


However, if you prefer to check if user is on translations the conservator way, there is already a global constant declared holding that value. These two lines are identical and we could spare a `querySelector()`

https://github.com/Mte90/GlotDict/blob/35d22f55dc3e496b1cab3b8fe87028360d07e154/js/glotdict.js#L24
https://github.com/Mte90/GlotDict/blob/35d22f55dc3e496b1cab3b8fe87028360d07e154/js/glotdict-functions.js#L510

Since this PR so gracefully implements `gd_user.is_on_translations`, could we make use of it in both cases and remove both of the above lines, checking if user is on translations only using `gd_user`?

**Comment by webaxones** [comment]
Hmm, my previous answer was an answer from a resting brain.
So yes, gd_notices_container at the beginning of glotdict.js is global but just used to access to a DOM element in this case, not to be used after. The thing that could be further done would be to check every global scope is necessary for the variables used in GD, but I think that could be further optimizations.

> gd_build_sticky_header(), ...when user is connected only? ...But that is subjective

Nope, objective: when you are not connected you automatically have a restricted number of rows for which a fixed header is not useful, or even triggers too early.

Of course the gd_user global can be used elsewhere: I just wanted to limit this PR to a feature, and not change everything :D 
So further PR can be done to optimize code with this kind of stuff :)

**Comment by vlad-timotei** [comment]
> when you are not connected you automatically have a restricted number of rows for which a fixed header is not useful, or even triggers too early.

That makes sense. Thanks for the info.

> Of course the gd_user global can be used elsewhere: I just wanted to limit this PR to a feature, and not change everything :D

Since this is code added in this PR, I think we can implement from the start the better way?

**Comment by webaxones** [comment]
We can, but multiple PRs can be done, nothing is in a hurry, not even a new version release. We don't all have the energy of youth :D (and I have let down my clients quite a bit in recent days :p )

**Comment by vlad-timotei** [comment]
> Are you sure the first one still works?
> Cause I use translations below to append the header…

It works, but since I know you want to keep variables with local scope I made sure of that in the last commit. 😁

**Comment by vlad-timotei** [comment]
All [tests](https://docs.google.com/document/d/1S2smv7Oq6H_Qox4PDAop0A7qDodq2qsmN2qVbi1Npuo/view) for this PR have the same results as 1.7.0. 🚀

**Pull request merged**
