### PR TITLE
Added Turkish Glossary

### PR DESCRIPTION
**Pull request by karalamalar**
Hi,

I prepared Turkish Glossary for you. I hope I did it right. :)

### CODE REVIEW

**Comment by Mte90** [comment]
Amazing the next public version will have also the turkish!
Little question that glossary is taken from glotpress? If yes i can add on https://github.com/Mte90/GlotDictJSON to mantein the glossary updated.

**Comment by karalamalar** [comment]
We worked on glossary on WordPress Global Translation Day but I couldn't find time to update GlotPress. Now you said that you can update automatically I'll update WP Glossary as soon as possible.

**Comment by Mte90** [comment]
Yeah with that script i can update automatically :-)

**Comment by karalamalar** [comment]
It's here: https://translate.wordpress.org/projects/wp/dev/tr/default/glossary

**Comment by Mte90** [comment]
added on https://github.com/Mte90/GlotDictJSON :-)

**Pull request merged**
