### PR TITLE
Update sk_SK.json

### PR DESCRIPTION
**Pull request by Angelo-Verona**
Update sk_SK dictionary

### CODE REVIEW

**Comment by Mte90** [comment]
Slovak is on https://github.com/Mte90/GlotDictJSON, so no worry if it is not updated because I update it before to publish a new release

**Comment by Mte90** [comment]
As i can see it is completelly different from the script generated by glotdict, maybe because on glotpress the glossary is not updated on that site?

**Comment by Angelo-Verona** [comment]
Oh, I see you are using glossary on GlotPress? We have Glossary on Google Drive and I converted that to JSON.

**Comment by Mte90** [comment]
Yes because my script works without problems.
The page is on https://translate.wordpress.org/projects/wp/dev/sk/default/glossary maybe update that so i can track that page respect a google docs.
In the meantime i approve your request

**Pull request merged**
