### PR TITLE
Replace JQuery with vanilla Javascript paying respect to ESlint rules and global variable conventions

### LINKED ISSUE #339: Improve code of settings.js by replacing last jQuery occurrences
Replace the jQuery code present in the settings.js file with native JS while respecting the ESLint rules as well as the gd_ prefix for any global, variable or function.

### PR DESCRIPTION
**Pull request by DillonKyleDev**
Fixes #339 @webaxones 

Replaced JQuery in `glotdict-settings.js` with vanilla Javascript.

I just started learning JQuery so pointers/corrections are appreciated! And of course if I missed any JQuery that's worth pointing out too!

### CODE REVIEW

**Review by webaxones — CHANGES_REQUESTED** [review]
Hi @DillonKyleDev,
Didn't expect that a problem added in the evening would have a PR so quickly :D
Just for information: we want to replace jQuery with native JS in the project to lighten the dependencies. This was not possible 5 years ago because browsers did not support modern JS, but now it does: we are just limiting ourselves to ES6 to avoid using babel/webpack.

About your PR I would like to ask you a few small changes:
`prependTo` doesn't exist in DOM API, it's some jQuery. `prepend` exist in DOM API. So this shouldn't work.
About `getElementById`: even though `getElementById` is a bit faster, I prefer to use `querySelector` everywhere as it is more readable to have the same way of accessing elements. Unless someone explains to me that it is better: I am not a JavaScript specialist, nor a specialist at all.
About your `append`: you must create elements before appending them. We avoid things like `innerHTML` or `insertAdjacentHTML` assignments for security reasons (a webextension is always risky).
So we create elements then define their innerText then append them.
Same as `getElementById` for `getElementsByClassName`. Yes they are good, but (it is my opinion and I agree to speak about it) `querySelector` allows to use exact CSS code and thus to avoid forgetting a `#` or a `.`

We haven't explained how to test a web extension. Did you manage to do it locally?
You just need to have the files in a folder, then, depending on your browser: on Chrome, chrome loads the unzipped extension in Extensions, on Firefox Debug a module (wheel in extensions).
I understand, however, that the most difficult in the tests is to understand how GlotDict and GlotPress work. It took me months to figure all this out lol

I'm very happy to have a new developer participating in this project. And I bet Daniele is even more so!

**Comment by Mte90** [comment]
> About `getElementById`: even though `getElementById` is a bit faster, I prefer to use `querySelector` everywhere as it is more readable to have the same way of accessing elements. Unless someone explains to me that it is better: I am not a JavaScript specialist, nor a specialist at all.

I am for querySelector too.

> I'm very happy to have a new developer participating in this project. And I bet Daniele is even more so!

Of course but before to do a pull request you should test your code itself. There is already a guide in the wiki https://github.com/Mte90/GlotDict/wiki/Test-extension-locally (that we can update if something is not clear).

**Comment by DillonKyleDev** [comment]
@webaxones and @Mte90 Thanks for all the helpful feedback!
I was just looking on MDN and didn't realize how versatile querySelector() is.  I'll switch them out.

> prependTo doesn't exist in DOM API, it's some jQuery. prepend exist in DOM API. So this shouldn't work.

Copy that ^

> So we create elements then define their innerText then append them.

Will do ^

> We haven't explained how to test a web extension. Did you manage to do it locally?

No you haven't, but that's on me! I should have read the docs more carefully before submitting any PRs.  I'll take a look at the testing resources and give it a go!

**Comment by webaxones** [comment]
>  I should have read the docs more carefully before submitting any PRs.

@DillonKyleDev, Every time I make a mistake I learn something. Every time I don't make a mistake I stagnate :D
When you are not sure, you can also comment with code, one of us will reply, etc. and then you will make your PR. Github is also a place to talk, ask questions, give answers, share ideas, and I do not deprive myself of it :)

**Comment by Mte90** [comment]
any updates @DillonKyleDev?

**Comment by vlad-timotei** [comment]
Fixed in #395

**Pull request closed without merging**
